trigger: none

schedules:
  - cron: "54 12 * * 3"
    displayName: "Weekly on Wednesday at 12:54"
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline-templates/pipeline-templates
      ref: refs/heads/support/v1.x

extends:
  template: renovate.yaml@templates
